# Generated by Django 4.1.4 on 2022-12-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='main field')),
                ('description', models.TextField(verbose_name="post's field")),
                ('author', models.CharField(max_length=100, verbose_name="author's name")),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
